### ISSUE TITLE
Add a PuliFactory interface

### ISSUE THREAD

**Issue by mnapoli** [puli/issues#100]
The `GeneratedPuliFactory` doesn't implement any interface, making it impossible to type-hint it in our code (since it's an auto-generated class).

For example I'd like to be able to type-hint the PuliFactory interface so that PhpStorm will autocomplete and validate method calls like this:

```php
public function getRepository(PuliFactory $factory)
{
    return $factory->createRepository();
}
```

Thoughts?

**Comment by webmozart** [comment]
This interface used to exist: https://github.com/puli/factory

The problem was, however, that the Puli factory is very modular. Both the core and plugins can add their own methods to the factory. Hence you'd need a factory class for every kind of object you want to create (`Puli\Repository\RepositoryFactory`, `Puli\Discovery\DiscoveryFactory`, ...) which I found a bit overkill given that you only need to use the factory in probably five lines of code of a typical project.

**Comment by webmozart** [comment]
What do you think @mnapoli?

**Comment by mnapoli** [comment]
Hey sorry :) I think this issue can be closed for now and maybe revisited later. I suspect it could be a problem for some other people, but it's probably not worth spending time on it if it's just me for now, and if it's just an autocompletion/IDE validation issue.

**Comment by XedinUnknown** [comment]
The way I addressed it is like this:

I have an interface [`FactoryInterface`][] which just defines how to generally interact with a factory, and promise a new instance every time. All factories accept a config container (in the general sense, which means it can be an `array` or `stdClass` too), which tells it how to create an instance.

I then create specializations of that interface, e.g. [`ContainerFactoryInterface`][], which promises to return a specific type - in this case a PSR-11 container. Of course, all factories can be implemented differently, but I know that container factories need at least some kind of map to be used to retrieve values for keys. In such cases, I define constants on the specialized factory interfaces to centralize the config keys, e.g. [`ContainerFactoryInterface::K_DATA`][]. Now, all container factories, regardless of implementation, know to accept the mapping (whatever it is) through that key. 

Compatibility between sub-type and super-type of the factory product is achieved by further specializing the factory, e.g. a [`MapFactoryInterface`][] may be used anywhere where `ContainerFactoryInterface` is expected, because anything that requires a container instance can work with a map instance.

I see how this is not ideal, but until we have generics adopted in PHP, this will have to do I guess.

[`FactoryInterface`]: https://github.com/Dhii/factory-interface/blob/develop/src/FactoryInterface.php
[`ContainerFactoryInterface`]: https://github.com/Dhii/data-container-interface/blob/develop/src/ContainerFactoryInterface.php
[`ContainerFactoryInterface::K_DATA`]: https://github.com/Dhii/data-container-interface/blob/develop/src/ContainerFactoryInterface.php#L20
[`MapFactoryInterface`]: https://github.com/Dhii/collections-interface/blob/develop/src/MapFactoryInterface.php
