### ISSUE TITLE
Store relative paths in path mapping repositories

### ISSUE THREAD

**Issue by webmozart** [puli/issues#117]
The path mapping repositories should store paths relative to the root directory instead of absolute system paths in order to facilitate portability. Depends on #116.

**Comment by mnapoli** [comment]
:+1: thank you for creating the issue. Detailing some use cases that break today because of absolute paths:

- `composer install`/`puli` is run on the host OS, and the application is run on a VM/container (Vagrant, Docker, etc.) where the paths are different
- the application is built on a system (e.g. in CI), and then the result is deployed in production (different paths)
- the application is copied or moved to another directory (e.g. I move the project on my dev machine for some reason)

**Comment by tgalopin** [comment]
That's a really good idea. Should I try to keep compatibility with pre beta 8 ?

**Comment by webmozart** [comment]
@tgalopin I don't think that's necessary
