### ISSUE TITLE
Directory Resource issues with path-mapping repository

### ISSUE THREAD

**Issue by temp** [puli/issues#121]
Create testcase:
```
$ mkdir testcase
$ cd testcase
$ mkdir -p src/Test/Resources/scripts/view/accordion
$ touch src/Test/Resources/scripts/view/accordion/test.js
$ puli.phar map test/mytest/scripts src/Test/Resources/scripts/
```

With path-mapping repository:
```
$ puli.phar ls test/mytest/scripts
view
$ puli.phar ls test/mytest/scripts/view
fatal: The resource /Users/swentz/test/src/Test/Resources/scripts/view/accordion does not exist.
```

With filesystem repository:
```
$ puli.phar config repository.type filesystem
$ rm -rf .puli/
$ puli.phar build
$ puli.phar ls test/mytest/scripts/view
accordion
```

**Comment by tgalopin** [comment]
Hi @temp,

It's working by me but I suspect that the fix for https://github.com/puli/issues/issues/113 solved your problem too. I fixed it in https://github.com/puli/repository/pull/51, which will be included in beta8 (soon to be released). Can you check with the lastest version of the repository if you still have the problem?

Thanks by advance!

**Comment by temp** [comment]
Works, tested with current repository. Thanks!

**Comment by webmozart** [comment]
Awesome, thanks  @temp! :)
