### ISSUE TITLE
Files get lost in PathMappingRepository

### ISSUE THREAD

**Issue by webmozart** [puli/issues#133]
The following test shows that files can get lost in PathMappingRepository when traversing children of a resource:

```
mkdir -p app/res/views
mkdir -p blog/res/views
touch app/res/views/layout.html.twig
touch blog/res/views/layout.html.twig
touch blog/res/views/index.html.twig
puli map /app app/res
puli map /acme/blog blog/res
puli map /acme/blog/views/layout.html.twig app/res/views/layout.html.twig
puli tree
/
├── acme
│   └── blog
│       └── views
│           └── layout.html.twig
└── app
    └── views
        └── layout.html.twig

7 resources
```

The `index.html.twig` file is missing from the output. The file can however be accessed:

```
puli cat /acme/blog/views/index.html.twig
```

**Comment by EmanueleMinotto** [comment]
The problem seems to be insinde the `::resolveFilesystemPaths` method, because `$path` exists in the key-value store but it's mapped to `null`.

Afaik two solutions are possible:

1. while mapping */acme/blog/views/layout.html.twig*, if a parent directory like */acme/blog* is already mapped and it is not `null` (or if a subdirectory is already mapped), than all the subpaths between them will be mapped too in the key-value store
2. at https://github.com/puli/repository/blob/1.0/src/PathMappingRepository.php#L212 `$path` will be splitted by `/` and iteratively all the preceding subpath are checked

**Comment by tgalopin** [comment]
Thanks for your research @EmanueleMinotto ! If you want to give this a try, I can give you a hand to build a PR. Would you be interested?

**Comment by EmanueleMinotto** [comment]
@tgalopin sure! :+1:
