### ISSUE TITLE
JsonFileStore second argument type

### ISSUE THREAD

**Issue by EmanueleMinotto** [puli/issues#142]
Currently there's a problem in the `GeneratedPuliFactory` because its generated with a `new JsonFileStore(__DIR__.'/bindings.json', true);` inside, while the current master version of the KeyValueStore accepts only an integer: https://github.com/webmozart/key-value-store/commit/196c4c8ff4c643e6ba9f954ed482629620ac88d4#diff-d59c34cb33c1eb8de6bace8a46cfea1cR63

I could create a PR, but I don't know if this problem should be solved inside `webmozart/key-value-store` or `puli/manager`.

**Comment by webmozart** [comment]
Actually this bug should already be fixed. Could you delete your `GeneratedPuliFactory` and run `puli build`? I think that should fix it.

**Comment by EmanueleMinotto** [comment]
This is the problem I'm having: https://travis-ci.org/puli/cli/jobs/90099887#L254
Is it related to this issue or to something else?

**Comment by tgalopin** [comment]
Is this still a problem?

**Comment by EmanueleMinotto** [comment]
@tgalopin yes, it is: https://travis-ci.org/puli/cli/jobs/95919602

**Comment by tgalopin** [comment]
This comes from the refactoring we did with @webmozart a few months ago: https://github.com/webmozart/key-value-store/pull/9

Now the stores are using a decorator for the cache instead of a constructor argument. However in the JsonKeyValueStoreGenerator we are still using the constructor argument: https://github.com/puli/manager/blob/master/src/Factory/Generator/KeyValueStore/JsonFileStoreGenerator.php#L49.

I'm creating a PR to fix this. That should solve this issue.

**Comment by webmozart** [comment]
This was fixed in #28.
