### ISSUE TITLE
Undefined offset 1 when CLI is installed with homebrew

### ISSUE THREAD

**Issue by sagikazarmark** [puli/issues#149]
The error occurs in the composer plugin (PuliPlugin.php:551). Very interesting that the `PULI_FACTORY_CLASS` in the generated autoload file gets the following value:

`/usr/bin/env php -d allow_url_fopen=On -d detect_unicode=Off /usr/local/Cellar/puli/1.0.0-beta9/libexec/puli.phar $*`

The problem solved itself when I installed the phar from github.

The problem occured in this repository: https://github.com/php-http/puli-test

**Comment by webmozart** [comment]
Thanks for the report @sagikazarmark! Is this problem reproducible? Can you provide me the precise steps to reproduce it?

**Comment by sagikazarmark** [comment]
Yes, I can:

1. Install puli from homebrew
2. Make sure it is actually used instead of the phar downloaded (should be `puli` added to your prefix from the homebrew directory which is `/usr/local/Cellar/puli/1.0.0-beta9/bin/` for me)
3. Test the project I linked above

I saw this in the puli binary. Strangely the factory class constant was set to this value (as mentioned above).

``` bash
#!/usr/bin/env bash
/usr/bin/env php -d allow_url_fopen=On -d detect_unicode=Off /usr/local/Cellar/puli/1.0.0-beta9/libexec/puli.phar $*
```

Hope this helps.

**Comment by webmozart** [comment]
Unfortunately I'm not working on a Mac and can't test this. @tgalopin @EmanueleMinotto can you check this?

**Comment by sagikazarmark** [comment]
Well, this is an environmental thing I guess, so I don't really now how to reproduce the issue under other platforms.

**Comment by tgalopin** [comment]
I'll check that :) .

**Comment by tgalopin** [comment]
I'm able to reproduce the problem, I'm working on it right now :) .

**Comment by sagikazarmark** [comment]
:+1:

**Comment by tgalopin** [comment]
The issue comes from the PuliRunner: [here](https://github.com/puli/composer-plugin/blob/master/src/PuliRunner.php#L64) we should be more clever than that. In our case, the PuliRunner detects the script `/usr/local/bin/puli` as a PHP script so it executes it with the PHP executable. However, this script is a Bash script so PHP just return the content of the script, which is `/usr/bin/env php -d allow_url_fopen=On -d detect_unicode=Off /usr/local/Cellar/puli/1.0.0-beta9/libexec/puli.phar $*`.

The runner is used by the Composer plugin to find some config values of Puli, such as the `PULI_FACTORY_CLASS` constant. As the runner always returns `/usr/bin/env php -d allow_url_fopen=On -d detect_unicode=Off /usr/local/Cellar/puli/1.0.0-beta9/libexec/puli.phar $*`, the plugin store this value in the constant and it fails.

To fix this, I suggest to look at the beginning of the script: if it starts with #!/usr/bin/env bash or something like that, we execute it directly, otherwise we use PHP.

What do you think @webmozart ?

**Comment by webmozart** [comment]
Hm. What about checking for the presence of `<?php`? I.e., if the opening tag is found, use `php` to execute, otherwise run directly?

**Comment by tgalopin** [comment]
That's a much better idea yes, it's easier to implement. I'm doing that and I check this night.

**Comment by tgalopin** [comment]
I just opened a PR to fix this. @sagikazarmark, can you test with this fix? If you can't, I'll do it this evening :) .

**Comment by sagikazarmark** [comment]
Works for me
