### ISSUE TITLE
Discovery thoughts

### ISSUE THREAD

**Issue by temp** [puli/issues#34]
Just tried puli discovery for our resources - great!
A few caveats still remain, though.

1. Are enabled packages are only pulled from the root puli file? Or from all puli-files, for example via composer installed packages? Since your wrote the scary-part in you blog-post, I guess only from root.
2. We have a lot of packages that are installed via composer, and every package has a puli file. All resources are organized through bindings, works fine. But the initial step of enabling all the packages was a pain in the a**. --enable --all would be nice ;-)
3. It would be nice if puli would show new bindings that might be enabled, and obsolete bindings that are still enabled. Or does puli handle obsolete bindings?
4. Is it possible to get the package names of the bindings received from $discovery->find($type)? "puli bind" shows them, but I didn't find anything in the Binding class...

Nevertheless - discovery is awesome!

**Comment by webmozart** [comment]
1. Yes, only from the root.
2. There will soon be a command `puli bind -i` (or similar) that let's you interactively enable/disable all new (i.e. neither enabled nor disabled) bindings. This command will be launched automatically when doing a composer update, so that you can enable/disable bindings right during installation.
3. I think obsolete enabled/disabled bindings aren't handled at the moment. Could you open another issue please?
4. Unfortunately not. The Discovery component itself is unaware of packages (which are a concept of the Repository Manager). What's the use case?

**Comment by temp** [comment]
1. Ok
2. Nice!
3. Done, #36
4. Use case has been eliminated. since my project is a project with a legacy extjs version, I need to do some ugly stuff for loading a whole bunch of javascript files. But I managed to work around this.

**Comment by temp** [comment]
Any news on 2)?
We have a lot of bindings, and it's a real pain to enable them all by hand.
Nice would be a "--enable all" or "--enable my/type", which enables all bindings for the specified type.
Interactive would be nice, too ;-)

**Comment by webmozart** [comment]
Just for reference: All bindings are enabled automatically by now.
