### ISSUE TITLE
Missing config-key "bootstrap-file"

### ISSUE THREAD

**Issue by stedekay** [puli/issues#94]
I am trying to run "composer update" of my Symfony application with the following puli relevant lines in composer.json:

```
"puli/symfony-bundle": "^1.0",
```

I am getting the following error:
> [Puli\ComposerPlugin\PuliRunnerException]
An error occurred while running: /usr/bin/php5 /usr/local/bin/puli config 'bootstrap-file' --parsed --no-ansi -vv (status 1): NoSuchConfigKeyException: The config key "bootstrap-file" does not exist.

I am using the puli.phar 1.0.0-beta5.

What am I missing?

**Comment by webmozart** [comment]
Thank you for reporting this issue @stedekay! The puli.phar 1.0.0-beta5 is not compatible with the latest dev version. The easiest fix is to require `puli/cli` in your project and use `vendor/bin/puli` for this project. If you do that, add `vendor/bin` to your path so that you can run simply `puli`:

```
$ export PATH="vendor/bin:$PATH"
```

Another fix is to set your minimum-stability to beta (not dev) so that the Puli deps are loaded in their beta version.

**Comment by stedekay** [comment]
Thanks for your reply. Now its working again.

**Comment by mnapoli** [comment]
Same here, just FYI for people running into this: updating the phar to beta7 (or above) fixes the problem.
